### ISSUE TITLE
Xiaomi Mi Smart Cube

### ISSUE THREAD

**Issue by badochov** [hakatashi/giiker#10]
Xiaomi recently released Xiaomi Mi Smart Cube. Unfortunatelly it doesn't work with this wrapper anymore. I managed to connect it after some modeifications(no name filter). But it doesnt show correct moves. I bet service and characteristic name are the same but data format must have changed. I'd be glad to collaborate to make it work.

**Comment by kabelbinder** [comment]
Did you check if the data format is similar to the format of the newer Giiker i3S versions or the Giiker i3SE? ([https://github.com/hakatashi/smart-cube-timer/issues/37](https://github.com/hakatashi/smart-cube-timer/issues/37))
If so, [my fork of the giiker repo](https://github.com/kabelbinder/giiker) might be helpful.
Or is it completely different?

**Comment by badochov** [comment]
@kabelbinder your repo works like a charm, I just needed to replace bluettoth filter with acceptAllDevices since this cube doesn't have name on bluetooth
