### ISSUE TITLE
Error in example code

### ISSUE THREAD

**Issue by bennetdev** [hakatashi/giiker#11]
The requested module '../index.js' does not provide an export named 'default'

**Comment by bennetdev** [comment]
const connect = async () => {
    const giiker = new Giiker();
    await giiker.connect();
    return giiker;
};

export {connect}

import {connect} from '../smartcube/js/libs/index.js';

**Comment by DarkKillerXL** [comment]
How would I go about fixing this? I'm trying to use this API but can't even get the example to work

Edit: I've got the same error you had in the beginning
