### ISSUE TITLE
Renamed cube cannot be connected

### ISSUE THREAD

**Issue by marianhlavac** [hakatashi/giiker#8]
Filtering bluetooth devices with name starting with `GiC` is a very naive way to display compatible devices.

https://github.com/hakatashi/giiker/blob/9a5f8f4b1cea4b8aca074747fd43fc5638dc10ae/index.js#L142-L145

Cubes can be renamed and thus renamed cubes cannot be displayed in the list of available devices.

**Comment by HannesMatthias** [comment]
I renamed my cube and I've no problem with connecting my cube.

**Comment by isaacrbeam** [comment]
@mmajko 
#7 Update with solution
